print("ucha khuberishvili")
print("data khuberishvili")
print("giorgi khuberisvhili")
print("luka khuberishvili")
print("nica khuberisvili")
print ("vici vici bevri dzma mkavs")
print("mamuka khuberishvili")
print("nana zeikidze")
print("GOA-Best")