num1 = (input("enter you first number:"))
num2 = (input("enter your second number:"))
num3 = (input("enter your third number:"))
num4 = (input("enter your fourth number:"))
num5 = (input("enter your fifth number:"))
print(int(num1) * int(num2) / int(num3) + int(num4) - int(num5))