num1 = (input("please enter your first number:"))
num2 = (input("please enter your second number"))
num3 = (input("please enter your third number:"))
num4 = (input("please enter your fourth number"))
num5 = (input("please enter your fifth number:"))
num6 = (input("please enter your sixth number"))
num7 = (input("please enter your seventh number:"))
num8 = (input("please enter your eight number"))
num9 = (input("please enter your ninth number:"))
num10 = (input("please enter your tenth number"))
num11 = (input("please enter your eleventh number:"))
num12 = (input("please enter your twelveth number"))
print(num1 == num2)
print(num3 < num4)
print(num5 >num6)
print(num7 != num8)
print(num9 <= num10)
print(num11 >= num12)