name = input("please enter your name")
lastname = input("please enter your last name")
age = input("please enter your age")
school = input("please enter yoour study")
height = input("please enter your height")
academy = input("please enter name of the best academy")
password = input("please enter your password")
print(name , lastname , age , school ,height , academy, password)